import type { Metadata } from 'next';
import { Inter as FontSans, Satisfy } from 'next/font/google';
import { Suspense } from 'react';

import { cn } from '@/lib/utils';

import { SWRProvider } from '../components/providers/SwrProvider';
import './globals.css';
import { ThemeProvider } from '@/components/providers/ThemeProvider';

const satisfy = Satisfy({
    weight: ['400'],
    subsets: ['latin']
});

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
                <Suspense>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <SWRProvider>{children}</SWRProvider>
                    </ThemeProvider>
                </Suspense>
            </body>
        </html>
    );
}
